### ISSUE TITLE
Support GitRepository for HelmRelease sources

### ISSUE THREAD

**Issue by tropnikovvl** [allenporter/flux-local#616] opened 2024-04-15 14:52 UTC
Hello!

I use flux-local as testing for my flux setup and getting an error.

```
FAILED clusters/devops::apps-stack::nexus/nexus - flux_local.exceptions.HelmException: Unable to find HelmRepository for flux-system-flux-system/./helm-charts/nexus-repository-manager for HelmRelease nexus (0 other HelmRepositories in --path)
```

I use some HelmReleases that link not to the helm repository, but to the git repository since they are in git.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
spec:
  chart:
    spec:
      chart: ./helm-charts/nexus-repository-manager
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  releaseName: nexus
```

Is it possible to expand the list of possible links for a HelmRelease?

**Comment by allenporter** [comment] 2024-04-15 15:02
Does that work in production? The chart name isn't a path but a kubernetes resource name so it doesn't look like a chart name format I've ever seen.

**Comment by allenporter** [comment] 2024-04-15 15:05
I see, I understand your comment now, apologies.

No that is not supported. Flux-local doesn't how to map that git repository to a local path and doesn't download for repos when run from the cli.

If this repo is local I could see it being made to work with '--sources'.  Does it work to run the 'helm template' locally on a chart specified like that? I'm not familiar with git backed charts, but if it's possible to expand with that cli then there may be a way to support this.

**Comment by allenporter** [comment] 2024-04-21 01:33
The next steps needed to support this would be:
- an example helm chart that can be included in a GitRepository for testing (only supporting the local repository)
- an example `helm template` command line to render the chart

I'm currently not looking into this, but if someone provided the above two things that could make it easier to get started adding support for this in flux-local.

**Comment by tropnikovvl** [comment] 2024-04-22 09:08
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/prometheus-community
  ref:
    branch: main
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/prometheus-blackbox-exporter
      sourceRef:
        kind: GitRepository
        name: prometheus-community
        namespace: flux-system
  releaseName: blackbox-exporter
```

**Comment by allenporter** [comment] 2024-04-22 11:09
Flux-local doesn't have built in support for downloading repositories to the local filesystem, unless it's built into helm already.

**Comment by tropnikovvl** [comment] 2024-04-22 19:19
Okay, I have created a repository with an example.
https://github.com/tropnikovvl/flux-local-test

**Comment by allenporter** [comment] 2024-04-23 05:05
I have a prototype working of this in #638 for a repo where the helm charts are in the same `GitRepository`.

I found it helpful to put the local chart directory in the `.krmignore` file.

**Comment by tropnikovvl** [comment] 2024-04-23 10:07
How will templates be done in this case?
Or will the test skip this helm release?

**Comment by allenporter** [comment] 2024-04-23 10:19
> How will helm template be done in this case?
> Or will the test skip this helm release?

In the referenced pr it runs against the local fit repo. For a remote repo it will fail since it can't download remote gitrepositories.

**Comment by allenporter** [comment] 2024-04-23 11:04
> > In the referenced pr it runs against the local fit repo. For a remote repo it will fail since it can't download remote gitrepositories.
> 
> I see you added cluster9, but I don't find a passed test for it.
> And that's why I don't yet understand how exactly it will work

You think I added this and it doesn't even actually do anything? :) The pr has additional tests included.

**Comment by allenporter** [comment] 2024-04-23 11:34
> I mean, I didn't find tests for cluster9 in the GitHub Actions run list.

There are tests for cluster9 in the pr, but not additionally running again in the actions.

**Comment by tropnikovvl** [comment] 2024-04-24 09:57
Hello @allenporter !

How can I test this for myself?

**Comment by allenporter** [comment] 2024-04-27 13:38
This has been released in https://github.com/allenporter/flux-local/releases/tag/5.1.0

**Comment by tropnikovvl** [comment] 2024-05-02 10:00
it works for me! Many thanks

**Closed** 2024-05-02 16:11 UTC

**Comment by allenporter** [comment] 2024-09-12 14:22
@FreekingDean yes, expecting to work. Yes, I'd prefer opening a new github repo with detail on how to reproduce the issue. I think the way I might frame the issue is that it works when using `test` or the CLI for getting objects e.g. `flux-local get hr` but you're seeing an issue with a `diff`? But either way, yes open an issue. We typically reproduce issues with a local repository setup that reproduces the problem (e.g. see  `tests/testdata/cluster9/` which is setup with a local chart and so more details like the exact commands you're running an example of the repo are typically needed.  (I don't personally use this feature myself)
